### ISSUE TITLE
Synopsysctl requires a certificate and key to use.

### ISSUE THREAD

**Issue by shrewbies** [blackducksoftware/synopsysctl#60]
**What happened**:

./synopsysctl create blackduck blackduck --namespace blackduck --persistent-storage=false --admin-password blackduck --user-password blackduck --seal-key abcdefghijlkmnopqrstuvwxyz012345 --version 2020.4.0

ERRO[0000] synopsyctl failed: required flag(s) "certificate-file-path", "certificate-key-file-path" not set

**What you expected to happen**:

I expected to not have to provide a certificate and key file as Black Duck will generate that for me.

**How to reproduce it (as minimally and precisely as possible)**:

./synopsysctl create blackduck blackduck --namespace blackduck --persistent-storage=false --admin-password blackduck --user-password blackduck --seal-key abcdefghijlkmnopqrstuvwxyz012345 --version 2020.4.0

**Environment (please complete the following information):**
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g: `cat /etc/os-release`):

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):

Linux sup-kube02.dc1.lan 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mphammer** [comment]
This will be resolved in synopsyctl 1.0.3 and Black Duck 2020.6.0

**Comment by mphammer** [comment]
PR: https://github.com/blackducksoftware/synopsysctl/pull/80
